#spring.application.name=mybatis
#??, ??, ????? ?? DB? ??? ????.
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data1?serverTimezone=Asia/Seoul
    username: root
    password: root123!

mybatis:
  type-aliases-package: com.example.mybatis.domain
  mapper-locations: classpath:mapper/*.xml